server:
  port: 8084

spring:
  application:
    name: team02payment
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
    consumer:
      group-id: team02-backend-group
      auto-offset-reset: earliest

      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer

      properties:
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "*"

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

order:
  events:
    topic: ${ORDER_EVENTS_TOPIC:order-events}

feign:
  client:
    config:
      default:
        connect-timeout: 5000
        read-timeout: 10000

---
spring:
  config:
    import: classpath:security/application-local.yml
    activate:
      on-profile: local

---
spring:
  config:
    import: classpath:security/application-dev.yml
    activate:
      on-profile: dev

---
spring:
  config:
    import: classpath:security/application-prod.yml
    activate:
      on-profile: prod

---
spring:
  config:
    import: classpath:security/application-test.yml
    activate:
      on-profile: test
