spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${PAYMENT_SERVICE_DB_URL}
    username: ${PAYMENT_SERVICE_DB_USERNAME}
    password: ${PAYMENT_SERVICE_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.MariaDBDialect
  flyway:
    enabled: false # 수동으로 Bean을 등록하기 위해 비활성화
  kafka:
    bootstrap-servers: localhost:9092

msa:
  gateway:
    url: http://localhost:8080

jwt:
  secret: ${JWT_SECRET}
