spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/payment
    username: root
    password: Wnsrns3224!
  jpa:
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.MariaDBDialect
  flyway:
    enabled: false # 수동으로 Bean을 등록하기 위해 비활성화
  kafka:
    bootstrap-servers: localhost:9092

msa:
  gateway:
    url: http://localhost:8080

jwt:
  secret: NftAtwgVLJ9x9RdM4khkxhpW8/jziqI155MMtQUW2ZFzulID+1bXCndYCGkwnlDhjIF6d+0jvYzgKgL2RfS2dA==

toss:
  clientKey: test_gck_docs_Ovk5rk1EwkEbP0W43n07xlzm
  secretKey: test_gsk_docs_OaPz8L5KdmQXkzRz3y47BMw6
