server:
  port: 8086
spring:
  application:
    name: team02review
  kafka:
    consumer:
      group-id: team02-backend-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
feign:
  client:
    config:
      default:
        connect-timeout: 5000
        read-timeout: 10000

# Actuator & Prometheus 설정
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  metrics:
    prometheus:
      metrics:
        export:
          enabled: true
    tags:
      application: ${spring.application.name}

---
spring:
  config:
    import: classpath:security/application-local.yml
    activate:
      on-profile: local
---
spring:
  config:
    import: classpath:security/application-dev.yml
    activate:
      on-profile: dev
---
spring:
  config:
    import: classpath:security/application-prod.yml
    activate:
      on-profile: prod
---
spring:
  config:
    import: classpath:security/application-test.yml
    activate:
      on-profile: test
