apiVersion: v1
kind: Service
metadata:
  name: delivery-service
  namespace: team02
spec:
  type: ClusterIP
  selector:
    app: delivery-service
  ports:
  - port: 8087
    targetPort: 8087
    protocol: TCP