apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: team02
bases:
  - ../../../base/gateway
  - ingress.yaml
images:
  - name: 093322228889.dkr.ecr.ap-northeast-2.amazonaws.com/team02-gateway
    newTag: b70da07 # CD에서 SHA로 자동 변경됨
