server:
  port: 8080
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${DB_URL_LOCAL}
    username: ${DB_USERNAME_LOCAL}
    password: ${DB_PASSWORD_LOCAL}
  jpa:
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.MariaDBDialect
  flyway:
    enabled: false # 수동으로 Bean을 등록하기 위해 비활성화

cloud:
  aws:
    credentials:
      access-key: "dummyKey"
      secret-key: "dummySecret"
    s3:
      bucket: your-bucket-name
    region:
      static: ap-northeast-2
    stack:
      auto: false

jwt:
  secret: ${JWT_SECRET_LOCAL}
  expiration: 3600000
