server:
  port: 8080
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${DB_URL_LOCAL:jdbc:mariadb://localhost:3306/asdf?characterEncoding=UTF-8&useUnicode=true}
    username: ${DB_USERNAME_LOCAL:root}
    password: ${DB_PASSWORD_LOCAL:}
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
  jpa:
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.MariaDBDialect

cors:
  allowed-origins: ${ORIGIN_URL_LOCAL:http://localhost:3000}

cloud:
  aws:
    credentials:
      access-key: dummy
      secret-key: dummy
    region:
      static: ap-northeast-2
    s3:
      bucket: dummy
