server:
  port: 8090
spring:
  application:
    name: team02demo
feign:
  client:
    config:
      default:
        connect-timeout: 5000
        read-timeout: 10000
---
spring:
  config:
    import: classpath:security/application-local.yml
    activate:
      on-profile: local
---
spring:
  config:
    import: classpath:security/application-dev.yml
    activate:
      on-profile: dev
---
spring:
  config:
    import: classpath:security/application-prod.yml
    activate:
      on-profile: prod
---
spring:
  config:
    import: classpath:security/application-test.yml
    activate:
      on-profile: test
