apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - user-service.yaml
 # - order-service.yaml
 # - payment-service.yaml
 # - owner-service.yaml
 # - review-service.yaml
 # - delivery-service.yaml
 # - notification-service.yaml
 # - gateway.yaml
 # - spring-config.yaml      # ConfigMap
