apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: team02
resources:
  - ../../../base/delivery-service
images:
  - name: 093322228889.dkr.ecr.ap-northeast-2.amazonaws.com/team02-delivery-service
    newTag: 83fa4ac # Actions가 SHA로 자동 변경
