spring:
  application:
    name: team02core

  datasource:
    url: jdbc:mariadb://localhost:8080/quickdeliver?serverTimezone=UTC
    username: root
    password: Wnsrns3224!
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  # CORS 허용 origins 추가

cors:
  allowed-origins: "*"
