apiVersion: v1
kind: Service
metadata:
  name: owner-service
  namespace: team02
spec:
  type: ClusterIP
  selector:
    app: owner-service
  ports:
  - port: 8081
    targetPort: 8081
    protocol: TCP