apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: team02  
spec:
  template:
    spec:
      containers:
        - name: user-service
          image: 093322228889.dkr.ecr.ap-northeast-2.amazonaws.com/team02-user-service:latest


