spring:
  application:
    name: team02

---

spring:
  config:
    import: classpath:security/application-local.yml
    activate:
      on-profile: local

---

spring:
  config:
    import: classpath:security/application-dev.yml
    activate:
      on-profile: dev

---

spring:
  config:
    import: classpath:security/application-prod.yml
    activate:
      on-profile: prod

---

spring:
  config:
    import: classpath:security/application-test.yml
    activate:
      on-profile: test

---

# 파일 업로드 설정
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# 커스텀 설정
app:
  s3:
    folder: store
