name: Order Service CI - Build & Test

on:
  pull_request:
    branches: [manifest/service]
    paths:
      - "msa/order-service/**"
      - "msa/libs/**"
      - ".github/workflows/order-service-ci-dev.yml"

env:
  SERVICE_NAME: order-service

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ env.SERVICE_NAME }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-${{ env.SERVICE_NAME }}-
            ${{ runner.os }}-gradle-

      - name: Build & Test ${{ env.SERVICE_NAME }}
        run: |
          cd msa/${{ env.SERVICE_NAME }}
          ../gradlew :${{ env.SERVICE_NAME }}:build

      - name: Upload test report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.SERVICE_NAME }}-test-report
          path: msa/${{ env.SERVICE_NAME }}/build/reports/tests/test
